import {
  FaNetworkWired,
  FaDownload,
  FaWrench,
  FaSearch,
  FaLock,
  FaLaptop,
  FaChartBar,
  FaRocket,
  FaBook,
  FaServer,
  FaDatabase,
  FaCloud,
  FaDesktop,
  FaCode,
  FaShieldAlt,
  FaTools,
  FaCogs,
  FaUserCog,
  FaUserShield,
  FaUserTie,
  FaUserGraduate,
  FaGraduationCap,
  FaChalkboardTeacher,
  FaClipboardList,
  FaClipboardCheck,
  FaFileAlt,
  FaFileCode,
  FaFilePdf,
  FaFileVideo,
  FaVideo,
  FaPlay,
  FaQuestion,
  FaQuestionCircle,
  FaInfoCircle,
  FaExclamationTriangle,
  FaExclamationCircle,
  FaPhone,
  FaMobileAlt,
  FaPhoneAlt,
  FaBug,
  FaBullhorn,
  FaCalculator,
  FaCamera,
  FaCertificate,
  FaChartLine,
  FaChartPie,
  FaCheckCircle,
  FaClipboard,
  FaClock,
  FaComments,
  FaCompass,
  FaCube,
  FaEdit,
  FaEnvelope,
  FaEye,
  FaFlag,
  FaFlask,
  FaFolder,
  FaGlobe,
  FaHammer,
  FaHeart,
  FaHome,
  FaIdCard,
  FaImage,
  FaKey,
  FaLightbulb,
  FaLink,
  FaMapMarkerAlt,
  FaMedal,
  FaMemory,
  FaMicrochip,
  FaMicroscope,
  FaMoneyBill,
  FaMusic,
  FaPalette,
  FaPaperPlane,
  FaPencilAlt,
  FaPrint,
  FaPuzzlePiece,
  FaQrcode,
  FaRecycle,
  FaRobot,
  FaSave,
  FaShareAlt,
  FaStar,
  FaStopwatch,
  FaTag,
  FaThumbsUp,
  FaTrophy,
  FaUpload,
  FaUsers,
  FaWifi,
  FaWindowMaximize,
  FaAdjust,
  FaAirFreshener,
  FaAmbulance,
  FaAnchor,
  FaApple,
  FaArchive,
  FaArrowDown,
  FaArrowLeft,
  FaArrowRight,
  FaArrowUp,
  FaArrowsAlt,
  FaAtom,
  FaAward,
  FaBaby,
  FaBackward,
  FaBan,
  FaBandAid,
  FaBarcode,
  FaBars,
  FaBatteryFull,
  FaBed,
  FaBeer,
  FaBell,
  FaBicycle,
  FaBinoculars,
  FaBirthdayCake,
  FaBlender,
  FaBolt,
  FaBomb,
  FaBone,
  FaBookmark,
  FaBookOpen,
  FaBowlingBall,
  FaBox,
  FaBoxOpen,
  FaBrain,
  FaBreadSlice,
  FaBriefcase,
  FaBroadcastTower,
  FaBroom,
  FaBrush,
  FaBus,
  FaBusinessTime,
  FaCalendar,
  FaCalendarAlt,
  FaCalendarCheck,
  FaCampground,
  FaCandyCane,
  FaCapsules,
  FaCar,
  FaCarrot,
  FaCartPlus,
  FaCat,
  FaChair,
  FaChartArea,
  FaChess,
  FaChild,
  FaChurch,
  FaCircle,
  FaCity,
  FaClinicMedical,
  FaCloudRain,
  FaCocktail,
  FaCoffee,
  FaCookie,
  FaCopy,
  FaCopyright,
  FaCouch,
  FaCreditCard,
  FaCrop,
  FaCross,
  FaCrown,
  FaCrutch,
  FaCut,
  FaDice,
  FaDna,
  FaDog,
  FaDollarSign,
  FaDonate,
  FaDoorClosed,
  FaDoorOpen,
  FaDove,
  FaDragon,
  FaDrum,
  FaDumbbell,
  FaEgg,
  FaEuroSign,
  FaExchangeAlt,
  FaExpand,
  FaFan,
  FaFastBackward,
  FaFastForward,
  FaFax,
  FaFeather,
  FaFemale,
  FaFighterJet,
  FaFileArchive,
  FaFileAudio,
  FaFileContract,
  FaFileDownload,
  FaFileExcel,
  FaFileExport,
  FaFileImage,
  FaFileImport,
  FaFileInvoice,
  FaFileMedical,
  FaFilePowerpoint,
  FaFileSignature,
  FaFileUpload,
  FaFileWord,
  FaFill,
  FaFilm,
  FaFilter,
  FaFingerprint,
  FaFire,
  FaFireAlt,
  FaFirstAid,
  FaFish,
  FaFistRaised,
  FaFolderOpen,
  FaFont,
  FaFootballBall,
  FaForward,
  FaFrog,
  FaFrown,
  FaGamepad,
  FaGasPump,
  FaGavel,
  FaGem,
  FaGhost,
  FaGift,
  FaGlasses,
  FaGolfBall,
  FaGuitar,
  FaHandHoldingHeart,
  FaHandPaper,
  FaHandPeace,
  FaHandPointDown,
  FaHandPointLeft,
  FaHandPointRight,
  FaHandPointUp,
  FaHandRock,
  FaHandScissors,
  FaHandSpock,
  FaHands,
  FaHandsHelping,
  FaHandshake,
  FaHardHat,
  FaHashtag,
  FaHdd,
  FaHeadphones,
  FaHeadset,
  FaHeartBroken,
  FaHelicopter,
  FaHighlighter,
  FaHiking,
  FaHistory,
  FaHockeyPuck,
  FaHollyBerry,
  FaHorse,
  FaHospital,
  FaHotdog,
  FaHotel,
  FaHourglass,
  FaHouseDamage,
  FaIceCream,
  FaIcicles,
  FaIcons,
  FaIdBadge,
  FaIgloo,
  FaInbox,
  FaIndent,
  FaIndustry,
  FaInfinity,
  FaItalic,
  FaJedi,
  FaJoint,
  FaKeyboard,
  FaKiss,
  FaKiwiBird,
  FaLanguage,
  FaLaugh,
  FaLayerGroup,
  FaLeaf,
  FaLemon,
  FaLevelDownAlt,
  FaLevelUpAlt,
  FaLifeRing,
  FaList,
  FaListAlt,
  FaListOl,
  FaListUl,
  FaLocationArrow,
  FaLockOpen,
  FaLongArrowAltDown,
  FaLongArrowAltLeft,
  FaLongArrowAltRight,
  FaLongArrowAltUp,
  FaLowVision,
  FaLuggageCart,
  FaLungs,
  FaMagic,
  FaMagnet,
  FaMailBulk,
  FaMale,
  FaMap,
  FaMapPin,
  FaMapSigns,
  FaMarker,
  FaMars,
  FaMask,
  FaMedkit,
  FaMeh,
  FaMeteor,
  FaMicrophone,
  FaMicrophoneAlt,
  FaMinus,
  FaMinusCircle,
  FaMinusSquare,
  FaMitten,
  FaMoneyBillAlt,
  FaMoneyCheck,
  FaMonument,
  FaMoon,
  FaMotorcycle,
  FaMountain,
  FaMouse,
  FaMugHot,
  FaNotesMedical,
  FaObjectGroup,
  FaObjectUngroup,
  FaOilCan,
  FaOm,
  FaOtter,
  FaOutdent,
  FaPaintBrush,
  FaPaintRoller,
  FaPaperclip,
  FaParachuteBox,
  FaParagraph,
  FaParking,
  FaPassport,
  FaPaste,
  FaPause,
  FaPaw,
  FaPeace,
  FaPen,
  FaPenAlt,
  FaPenFancy,
  FaPenNib,
  FaPenSquare,
  FaPencilRuler,
  FaPeopleCarry,
  FaPercent,
  FaPersonBooth,
  FaPiggyBank,
  FaPills,
  FaPizzaSlice,
  FaPlane,
  FaPlaneArrival,
  FaPlaneDeparture,
  FaPlayCircle,
  FaPlug,
  FaPlus,
  FaPlusCircle,
  FaPlusSquare,
  FaPodcast,
  FaPoll,
  FaPoo,
  FaPortrait,
  FaPoundSign,
  FaPowerOff,
  FaPray,
  FaPrayingHands,
  FaPrescription,
  FaPrescriptionBottle,
  FaPrescriptionBottleAlt,
  FaProjectDiagram,
  FaPumpMedical,
  FaPumpSoap,
  FaQuoteLeft,
  FaQuoteRight,
  FaRandom,
  FaReceipt,
  FaRedo,
  FaRegistered,
  FaReply,
  FaReplyAll,
  FaRibbon,
  FaRing,
  FaRoad,
  FaRobot as FaRobotAlt,
  FaRoute,
  FaRss,
  FaRuler,
  FaRulerCombined,
  FaRulerHorizontal,
  FaRulerVertical,
  FaRunning,
  FaSadCry,
  FaSadTear,
  FaSatellite,
  FaSatelliteDish,
  FaSchool,
  FaScrewdriver,
  FaScroll,
  FaSdCard,
  FaSeedling,
  FaShapes,
  FaShareSquare,
  FaShip,
  FaShippingFast,
  FaShoppingBag,
  FaShoppingBasket,
  FaShoppingCart,
  FaShower,
  FaShuttleVan,
  FaSign,
  FaSignInAlt,
  FaSignLanguage,
  FaSignOutAlt,
  FaSignal,
  FaSignature,
  FaSimCard,
  FaSitemap,
  FaSkating,
  FaSkiing,
  FaSkull,
  FaSkullCrossbones,
  FaSlash,
  FaSleigh,
  FaSlidersH,
  FaSmile,
  FaSmileBeam,
  FaSmileWink,
  FaSmog,
  FaSmoking,
  FaSmokingBan,
  FaSms,
  FaSnowboarding,
  FaSnowflake,
  FaSnowman,
  FaSnowplow,
  FaSocks,
  FaSolarPanel,
  FaSort,
  FaSortAlphaDown,
  FaSortAlphaDownAlt,
  FaSortAlphaUp,
  FaSortAlphaUpAlt,
  FaSortAmountDown,
  FaSortAmountDownAlt,
  FaSortAmountUp,
  FaSortAmountUpAlt,
  FaSortDown,
  FaSortNumericDown,
  FaSortNumericDownAlt,
  FaSortNumericUp,
  FaSortNumericUpAlt,
  FaSortUp,
  FaSpa,
  FaSpaceShuttle,
  FaSpellCheck,
  FaSpider,
  FaSpinner,
  FaSplotch,
  FaSprayCan,
  FaSquare,
  FaSquareFull,
  FaSquareRootAlt,
  FaStamp,
  FaStarAndCrescent,
  FaStarHalf,
  FaStarHalfAlt,
  FaStarOfDavid,
  FaStarOfLife,
  FaStepBackward,
  FaStepForward,
  FaStethoscope,
  FaStickyNote,
  FaStop,
  FaStopCircle,
  FaStore,
  FaStoreAlt,
  FaStream,
  FaStreetView,
  FaStrikethrough,
  FaStroopwafel,
  FaSubscript,
  FaSubway,
  FaSuitcase,
  FaSuitcaseRolling,
  FaSun,
  FaSuperscript,
  FaSuperpowers,
  FaSurprise,
  FaSwatchbook,
  FaSwimmer,
  FaSwimmingPool,
  FaSynagogue,
  FaSync,
  FaSyncAlt,
  FaSyringe,
  FaTable,
  FaTableTennis,
  FaTablet,
  FaTabletAlt,
  FaTablets,
  FaTachometerAlt,
  FaTags,
  FaTape,
  FaTasks,
  FaTaxi,
  FaTeeth,
  FaTeethOpen,
  FaTemperatureHigh,
  FaTemperatureLow,
  FaTerminal,
  FaTextHeight,
  FaTextWidth,
  FaTheaterMasks,
  FaThermometer,
  FaThermometerEmpty,
  FaThermometerFull,
  FaThermometerHalf,
  FaThermometerQuarter,
  FaThermometerThreeQuarters,
  FaThumbsDown,
  FaThumbsUp as FaThumbsUpAlt,
  FaTicketAlt,
  FaTimes,
  FaTimesCircle,
  FaTint,
  FaTintSlash,
  FaTired,
  FaToggleOff,
  FaToggleOn,
  FaToilet,
  FaToiletPaper,
  FaToolbox,
  FaTooth,
  FaTrademark,
  FaTrafficLight,
  FaTrain,
  FaTram,
  FaTransgender,
  FaTransgenderAlt,
  FaTrash,
  FaTrashAlt,
  FaTrashRestore,
  FaTrashRestoreAlt,
  FaTree,
  FaTruck,
  FaTruckLoading,
  FaTruckMonster,
  FaTruckMoving,
  FaTruckPickup,
  FaTshirt,
  FaTty,
  FaTv,
  FaUmbrella,
  FaUmbrellaBeach,
  FaUnderline,
  FaUndo,
  FaUndoAlt,
  FaUniversalAccess,
  FaUniversity,
  FaUnlink,
  FaUnlock,
  FaUnlockAlt,
  FaUpload as FaUploadAlt,
  FaUser,
  FaUserAlt,
  FaUserAltSlash,
  FaUserAstronaut,
  FaUserCheck,
  FaUserCircle,
  FaUserClock,
  FaUserEdit,
  FaUserFriends,
  FaUserInjured,
  FaUserLock,
  FaUserMd,
  FaUserMinus,
  FaUserNinja,
  FaUserNurse,
  FaUserPlus,
  FaUserSecret,
  FaUserSlash,
  FaUserTag,
  FaUserTimes,
  FaUtensils,
  FaUtensilSpoon,
  FaVenus,
  FaVenusMars,
  FaVial,
  FaVials,
  FaVideoSlash,
  FaVoicemail,
  FaVolleyballBall,
  FaVolumeDown,
  FaVolumeMute,
  FaVolumeOff,
  FaVolumeUp,
  FaWalking,
  FaWallet,
  FaWarehouse,
  FaWater,
  FaWeight,
  FaWeightHanging,
  FaWheelchair,
  FaWineBottle,
  FaWineGlass,
  FaWineGlassAlt,
  FaWonSign,
  FaWrench as FaWrenchAlt,
  FaXRay,
  FaYenSign,
  FaYinYang
} from 'react-icons/fa';

// Map icon names to components (sorted alphabetically)
export const iconComponentMap = {
  'Adjust': FaAdjust,
  'Air Freshener': FaAirFreshener,
  'Ambulance': FaAmbulance,
  'Anchor': FaAnchor,
  'Apple': FaApple,
  'Archive': FaArchive,
  'Arrow Down': FaArrowDown,
  'Arrow Left': FaArrowLeft,
  'Arrow Right': FaArrowRight,
  'Arrow Up': FaArrowUp,
  'Arrows': FaArrowsAlt,
  'Atom': FaAtom,
  'Award': FaAward,
  'Baby': FaBaby,
  'Backward': FaBackward,
  'Ban': FaBan,
  'Band Aid': FaBandAid,
  'Barcode': FaBarcode,
  'Bars': FaBars,
  'Battery': FaBatteryFull,
  'Bed': FaBed,
  'Beer': FaBeer,
  'Bell': FaBell,
  'Bicycle': FaBicycle,
  'Binoculars': FaBinoculars,
  'Birthday Cake': FaBirthdayCake,
  'Blender': FaBlender,
  'Bolt': FaBolt,
  'Bomb': FaBomb,
  'Bone': FaBone,
  'Book': FaBook,
  'Bookmark': FaBookmark,
  'Book Open': FaBookOpen,
  'Bowling Ball': FaBowlingBall,
  'Box': FaBox,
  'Box Open': FaBoxOpen,
  'Brain': FaBrain,
  'Bread Slice': FaBreadSlice,
  'Briefcase': FaBriefcase,
  'Broadcast Tower': FaBroadcastTower,
  'Broom': FaBroom,
  'Brush': FaBrush,
  'Bug': FaBug,
  'Bullhorn': FaBullhorn,
  'Bus': FaBus,
  'Business Time': FaBusinessTime,
  'Calculator': FaCalculator,
  'Calendar': FaCalendar,
  'Calendar Alt': FaCalendarAlt,
  'Calendar Check': FaCalendarCheck,
  'Campground': FaCampground,
  'Candy Cane': FaCandyCane,
  'Capsules': FaCapsules,
  'Car': FaCar,
  'Carrot': FaCarrot,
  'Cart Plus': FaCartPlus,
  'Cat': FaCat,
  'Chair': FaChair,
  'Chart': FaChartBar,
  'Chart Area': FaChartArea,
  'Chart Line': FaChartLine,
  'Chart Pie': FaChartPie,
  'Check Circle': FaCheckCircle,
  'Chess': FaChess,
  'Child': FaChild,
  'Church': FaChurch,
  'Circle': FaCircle,
  'City': FaCity,
  'Clinic Medical': FaClinicMedical,
  'Clipboard': FaClipboard,
  'Clipboard Check': FaClipboardCheck,
  'Clipboard List': FaClipboardList,
  'Clock': FaClock,
  'Cloud': FaCloud,
  'Cloud Rain': FaCloudRain,
  'Cocktail': FaCocktail,
  'Code': FaCode,
  'Coffee': FaCoffee,
  'Cogs': FaCogs,
  'Comments': FaComments,
  'Compass': FaCompass,
  'Cookie': FaCookie,
  'Copy': FaCopy,
  'Copyright': FaCopyright,
  'Couch': FaCouch,
  'Credit Card': FaCreditCard,
  'Crop': FaCrop,
  'Cross': FaCross,
  'Crown': FaCrown,
  'Crutch': FaCrutch,
  'Cube': FaCube,
  'Cut': FaCut,
  'Database': FaDatabase,
  'Desktop': FaDesktop,
  'Dice': FaDice,
  'DNA': FaDna,
  'Dog': FaDog,
  'Dollar Sign': FaDollarSign,
  'Donate': FaDonate,
  'Door Closed': FaDoorClosed,
  'Door Open': FaDoorOpen,
  'Dove': FaDove,
  'Download': FaDownload,
  'Dragon': FaDragon,
  'Drum': FaDrum,
  'Dumbbell': FaDumbbell,
  'Edit': FaEdit,
  'Egg': FaEgg,
  'Envelope': FaEnvelope,
  'Euro Sign': FaEuroSign,
  'Exchange': FaExchangeAlt,
  'Expand': FaExpand,
  'Eye': FaEye,
  'Fan': FaFan,
  'Fast Backward': FaFastBackward,
  'Fast Forward': FaFastForward,
  'Fax': FaFax,
  'Feather': FaFeather,
  'Female': FaFemale,
  'Fighter Jet': FaFighterJet,
  'File': FaFileAlt,
  'File Archive': FaFileArchive,
  'File Audio': FaFileAudio,
  'File Code': FaFileCode,
  'File Contract': FaFileContract,
  'File Download': FaFileDownload,
  'File Excel': FaFileExcel,
  'File Export': FaFileExport,
  'File Image': FaFileImage,
  'File Import': FaFileImport,
  'File Invoice': FaFileInvoice,
  'File Medical': FaFileMedical,
  'File Powerpoint': FaFilePowerpoint,
  'File Signature': FaFileSignature,
  'File Upload': FaFileUpload,
  'File Word': FaFileWord,
  'Fill': FaFill,
  'Film': FaFilm,
  'Filter': FaFilter,
  'Fingerprint': FaFingerprint,
  'Fire': FaFire,
  'Fire Alt': FaFireAlt,
  'First Aid': FaFirstAid,
  'Fish': FaFish,
  'Fist Raised': FaFistRaised,
  'Flag': FaFlag,
  'Flask': FaFlask,
  'Folder': FaFolder,
  'Folder Open': FaFolderOpen,
  'Font': FaFont,
  'Football Ball': FaFootballBall,
  'Forward': FaForward,
  'Frog': FaFrog,
  'Frown': FaFrown,
  'Gamepad': FaGamepad,
  'Gas Pump': FaGasPump,
  'Gavel': FaGavel,
  'Gem': FaGem,
  'Ghost': FaGhost,
  'Gift': FaGift,
  'Glasses': FaGlasses,
  'Globe': FaGlobe,
  'Golf Ball': FaGolfBall,
  'Graduate': FaUserGraduate,
  'Graduation Cap': FaGraduationCap,
  'Guitar': FaGuitar,
  'Hammer': FaHammer,
  'Hand Holding Heart': FaHandHoldingHeart,
  'Hand Paper': FaHandPaper,
  'Hand Peace': FaHandPeace,
  'Hand Point Down': FaHandPointDown,
  'Hand Point Left': FaHandPointLeft,
  'Hand Point Right': FaHandPointRight,
  'Hand Point Up': FaHandPointUp,
  'Hand Rock': FaHandRock,
  'Hand Scissors': FaHandScissors,
  'Hand Spock': FaHandSpock,
  'Hands': FaHands,
  'Hands Helping': FaHandsHelping,
  'Handshake': FaHandshake,
  'Hard Hat': FaHardHat,
  'Hashtag': FaHashtag,
  'HDD': FaHdd,
  'Headphones': FaHeadphones,
  'Headset': FaHeadset,
  'Heart': FaHeart,
  'Heart Broken': FaHeartBroken,
  'Helicopter': FaHelicopter,
  'Highlighter': FaHighlighter,
  'Hiking': FaHiking,
  'History': FaHistory,
  'Hockey Puck': FaHockeyPuck,
  'Holly Berry': FaHollyBerry,
  'Home': FaHome,
  'Horse': FaHorse,
  'Hospital': FaHospital,
  'Hotdog': FaHotdog,
  'Hotel': FaHotel,
  'Hourglass': FaHourglass,
  'House Damage': FaHouseDamage,
  'Ice Cream': FaIceCream,
  'Icicles': FaIcicles,
  'Icons': FaIcons,
  'ID Badge': FaIdBadge,
  'ID Card': FaIdCard,
  'Igloo': FaIgloo,
  'Image': FaImage,
  'Inbox': FaInbox,
  'Indent': FaIndent,
  'Industry': FaIndustry,
  'Infinity': FaInfinity,
  'Info': FaInfoCircle,
  'Italic': FaItalic,
  'Jedi': FaJedi,
  'Joint': FaJoint,
  'Key': FaKey,
  'Keyboard': FaKeyboard,
  'Kiss': FaKiss,
  'Kiwi Bird': FaKiwiBird,
  'Language': FaLanguage,
  'Laptop': FaLaptop,
  'Laugh': FaLaugh,
  'Layer Group': FaLayerGroup,
  'Leaf': FaLeaf,
  'Lemon': FaLemon,
  'Level Down': FaLevelDownAlt,
  'Level Up': FaLevelUpAlt,
  'Life Ring': FaLifeRing,
  'Lightbulb': FaLightbulb,
  'Link': FaLink,
  'List': FaList,
  'List Alt': FaListAlt,
  'List Ordered': FaListOl,
  'List Unordered': FaListUl,
  'Location Arrow': FaLocationArrow,
  'Lock': FaLock,
  'Lock Open': FaLockOpen,
  'Long Arrow Down': FaLongArrowAltDown,
  'Long Arrow Left': FaLongArrowAltLeft,
  'Long Arrow Right': FaLongArrowAltRight,
  'Long Arrow Up': FaLongArrowAltUp,
  'Low Vision': FaLowVision,
  'Luggage Cart': FaLuggageCart,
  'Lungs': FaLungs,
  'Magic': FaMagic,
  'Magnet': FaMagnet,
  'Mail Bulk': FaMailBulk,
  'Male': FaMale,
  'Map': FaMap,
  'Map Marker': FaMapMarkerAlt,
  'Map Pin': FaMapPin,
  'Map Signs': FaMapSigns,
  'Marker': FaMarker,
  'Mars': FaMars,
  'Mask': FaMask,
  'Medal': FaMedal,
  'Medkit': FaMedkit,
  'Meh': FaMeh,
  'Memory': FaMemory,
  'Meteor': FaMeteor,
  'Microchip': FaMicrochip,
  'Microphone': FaMicrophone,
  'Microphone Alt': FaMicrophoneAlt,
  'Microscope': FaMicroscope,
  'Minus': FaMinus,
  'Minus Circle': FaMinusCircle,
  'Minus Square': FaMinusSquare,
  'Mitten': FaMitten,
  'Mobile': FaMobileAlt,
  'Money Bill': FaMoneyBill,
  'Money Bill Alt': FaMoneyBillAlt,
  'Money Check': FaMoneyCheck,
  'Monument': FaMonument,
  'Moon': FaMoon,
  'Motorcycle': FaMotorcycle,
  'Mountain': FaMountain,
  'Mouse': FaMouse,
  'Mug Hot': FaMugHot,
  'Music': FaMusic,
  'Network': FaNetworkWired,
  'Notes Medical': FaNotesMedical,
  'Object Group': FaObjectGroup,
  'Object Ungroup': FaObjectUngroup,
  'Oil Can': FaOilCan,
  'Om': FaOm,
  'Otter': FaOtter,
  'Outdent': FaOutdent,
  'Paint Brush': FaPaintBrush,
  'Paint Roller': FaPaintRoller,
  'Palette': FaPalette,
  'Paper Plane': FaPaperPlane,
  'Paperclip': FaPaperclip,
  'Parachute Box': FaParachuteBox,
  'Paragraph': FaParagraph,
  'Parking': FaParking,
  'Passport': FaPassport,
  'Paste': FaPaste,
  'Pause': FaPause,
  'Paw': FaPaw,
  'Peace': FaPeace,
  'PDF': FaFilePdf,
  'Pen': FaPen,
  'Pen Alt': FaPenAlt,
  'Pen Fancy': FaPenFancy,
  'Pen Nib': FaPenNib,
  'Pen Square': FaPenSquare,
  'Pencil': FaPencilAlt,
  'Pencil Ruler': FaPencilRuler,
  'People Carry': FaPeopleCarry,
  'Percent': FaPercent,
  'Person Booth': FaPersonBooth,
  'Phone': FaPhone,
  'Phone Alt': FaPhoneAlt,
  'Piggy Bank': FaPiggyBank,
  'Pills': FaPills,
  'Pizza Slice': FaPizzaSlice,
  'Plane': FaPlane,
  'Plane Arrival': FaPlaneArrival,
  'Plane Departure': FaPlaneDeparture,
  'Play': FaPlay,
  'Play Circle': FaPlayCircle,
  'Plug': FaPlug,
  'Plus': FaPlus,
  'Plus Circle': FaPlusCircle,
  'Plus Square': FaPlusSquare,
  'Podcast': FaPodcast,
  'Poll': FaPoll,
  'Poo': FaPoo,
  'Portrait': FaPortrait,
  'Pound Sign': FaPoundSign,
  'Power Off': FaPowerOff,
  'Pray': FaPray,
  'Praying Hands': FaPrayingHands,
  'Prescription': FaPrescription,
  'Prescription Bottle': FaPrescriptionBottle,
  'Prescription Bottle Alt': FaPrescriptionBottleAlt,
  'Print': FaPrint,
  'Project Diagram': FaProjectDiagram,
  'Pump Medical': FaPumpMedical,
  'Pump Soap': FaPumpSoap,
  'Puzzle Piece': FaPuzzlePiece,
  'QR Code': FaQrcode,
  'Question': FaQuestion,
  'Question Circle': FaQuestionCircle,
  'Quote Left': FaQuoteLeft,
  'Quote Right': FaQuoteRight,
  'Random': FaRandom,
  'Receipt': FaReceipt,
  'Recycle': FaRecycle,
  'Redo': FaRedo,
  'Registered': FaRegistered,
  'Reply': FaReply,
  'Reply All': FaReplyAll,
  'Ribbon': FaRibbon,
  'Ring': FaRing,
  'Road': FaRoad,
  'Robot': FaRobot,
  'Rocket': FaRocket,
  'Route': FaRoute,
  'RSS': FaRss,
  'Ruler': FaRuler,
  'Ruler Combined': FaRulerCombined,
  'Ruler Horizontal': FaRulerHorizontal,
  'Ruler Vertical': FaRulerVertical,
  'Running': FaRunning,
  'Sad Cry': FaSadCry,
  'Sad Tear': FaSadTear,
  'Satellite': FaSatellite,
  'Satellite Dish': FaSatelliteDish,
  'Save': FaSave,
  'School': FaSchool,
  'Screwdriver': FaScrewdriver,
  'Scroll': FaScroll,
  'SD Card': FaSdCard,
  'Search': FaSearch,
  'Seedling': FaSeedling,
  'Server': FaServer,
  'Shapes': FaShapes,
  'Share': FaShareAlt,
  'Share Square': FaShareSquare,
  'Shield': FaShieldAlt,
  'Ship': FaShip,
  'Shipping Fast': FaShippingFast,
  'Shopping Bag': FaShoppingBag,
  'Shopping Basket': FaShoppingBasket,
  'Shopping Cart': FaShoppingCart,
  'Shower': FaShower,
  'Shuttle Van': FaShuttleVan,
  'Sign': FaSign,
  'Sign In': FaSignInAlt,
  'Sign Language': FaSignLanguage,
  'Sign Out': FaSignOutAlt,
  'Signal': FaSignal,
  'Signature': FaSignature,
  'SIM Card': FaSimCard,
  'Sitemap': FaSitemap,
  'Skating': FaSkating,
  'Skiing': FaSkiing,
  'Skull': FaSkull,
  'Skull Crossbones': FaSkullCrossbones,
  'Slash': FaSlash,
  'Sleigh': FaSleigh,
  'Sliders': FaSlidersH,
  'Smile': FaSmile,
  'Smile Beam': FaSmileBeam,
  'Smile Wink': FaSmileWink,
  'Smog': FaSmog,
  'Smoking': FaSmoking,
  'Smoking Ban': FaSmokingBan,
  'SMS': FaSms,
  'Snowboarding': FaSnowboarding,
  'Snowflake': FaSnowflake,
  'Snowman': FaSnowman,
  'Snowplow': FaSnowplow,
  'Socks': FaSocks,
  'Solar Panel': FaSolarPanel,
  'Sort': FaSort,
  'Sort Alpha Down': FaSortAlphaDown,
  'Sort Alpha Down Alt': FaSortAlphaDownAlt,
  'Sort Alpha Up': FaSortAlphaUp,
  'Sort Alpha Up Alt': FaSortAlphaUpAlt,
  'Sort Amount Down': FaSortAmountDown,
  'Sort Amount Down Alt': FaSortAmountDownAlt,
  'Sort Amount Up': FaSortAmountUp,
  'Sort Amount Up Alt': FaSortAmountUpAlt,
  'Sort Down': FaSortDown,
  'Sort Numeric Down': FaSortNumericDown,
  'Sort Numeric Down Alt': FaSortNumericDownAlt,
  'Sort Numeric Up': FaSortNumericUp,
  'Sort Numeric Up Alt': FaSortNumericUpAlt,
  'Sort Up': FaSortUp,
  'Spa': FaSpa,
  'Space Shuttle': FaSpaceShuttle,
  'Spell Check': FaSpellCheck,
  'Spider': FaSpider,
  'Spinner': FaSpinner,
  'Splotch': FaSplotch,
  'Spray Can': FaSprayCan,
  'Square': FaSquare,
  'Square Full': FaSquareFull,
  'Square Root': FaSquareRootAlt,
  'Stamp': FaStamp,
  'Star': FaStar,
  'Star And Crescent': FaStarAndCrescent,
  'Star Half': FaStarHalf,
  'Star Half Alt': FaStarHalfAlt,
  'Star Of David': FaStarOfDavid,
  'Star Of Life': FaStarOfLife,
  'Step Backward': FaStepBackward,
  'Step Forward': FaStepForward,
  'Stethoscope': FaStethoscope,
  'Sticky Note': FaStickyNote,
  'Stop': FaStop,
  'Stop Circle': FaStopCircle,
  'Stopwatch': FaStopwatch,
  'Store': FaStore,
  'Store Alt': FaStoreAlt,
  'Stream': FaStream,
  'Street View': FaStreetView,
  'Strikethrough': FaStrikethrough,
  'Stroopwafel': FaStroopwafel,
  'Subscript': FaSubscript,
  'Subway': FaSubway,
  'Suitcase': FaSuitcase,
  'Suitcase Rolling': FaSuitcaseRolling,
  'Sun': FaSun,
  'Superscript': FaSuperscript,
  'Superpowers': FaSuperpowers,
  'Surprise': FaSurprise,
  'Swatchbook': FaSwatchbook,
  'Swimmer': FaSwimmer,
  'Swimming Pool': FaSwimmingPool,
  'Synagogue': FaSynagogue,
  'Sync': FaSync,
  'Sync Alt': FaSyncAlt,
  'Syringe': FaSyringe,
  'Table': FaTable,
  'Table Tennis': FaTableTennis,
  'Tablet': FaTablet,
  'Tablet Alt': FaTabletAlt,
  'Tablets': FaTablets,
  'Tachometer': FaTachometerAlt,
  'Tag': FaTag,
  'Tags': FaTags,
  'Tape': FaTape,
  'Tasks': FaTasks,
  'Taxi': FaTaxi,
  'Teacher': FaChalkboardTeacher,
  'Teeth': FaTeeth,
  'Teeth Open': FaTeethOpen,
  'Temperature High': FaTemperatureHigh,
  'Temperature Low': FaTemperatureLow,
  'Terminal': FaTerminal,
  'Text Height': FaTextHeight,
  'Text Width': FaTextWidth,
  'Theater Masks': FaTheaterMasks,
  'Thermometer': FaThermometer,
  'Thermometer Empty': FaThermometerEmpty,
  'Thermometer Full': FaThermometerFull,
  'Thermometer Half': FaThermometerHalf,
  'Thermometer Quarter': FaThermometerQuarter,
  'Thermometer Three Quarters': FaThermometerThreeQuarters,
  'Thumbs Down': FaThumbsDown,
  'Thumbs Up': FaThumbsUp,
  'Ticket': FaTicketAlt,
  'Times': FaTimes,
  'Times Circle': FaTimesCircle,
  'Tint': FaTint,
  'Tint Slash': FaTintSlash,
  'Tired': FaTired,
  'Toggle Off': FaToggleOff,
  'Toggle On': FaToggleOn,
  'Toilet': FaToilet,
  'Toilet Paper': FaToiletPaper,
  'Toolbox': FaToolbox,
  'Tools': FaTools,
  'Tooth': FaTooth,
  'Trademark': FaTrademark,
  'Traffic Light': FaTrafficLight,
  'Train': FaTrain,
  'Tram': FaTram,
  'Transgender': FaTransgender,
  'Transgender Alt': FaTransgenderAlt,
  'Trash': FaTrash,
  'Trash Alt': FaTrashAlt,
  'Trash Restore': FaTrashRestore,
  'Trash Restore Alt': FaTrashRestoreAlt,
  'Tree': FaTree,
  'Trophy': FaTrophy,
  'Truck': FaTruck,
  'Truck Loading': FaTruckLoading,
  'Truck Monster': FaTruckMonster,
  'Truck Moving': FaTruckMoving,
  'Truck Pickup': FaTruckPickup,
  'T-shirt': FaTshirt,
  'TTY': FaTty,
  'TV': FaTv,
  'Umbrella': FaUmbrella,
  'Umbrella Beach': FaUmbrellaBeach,
  'Underline': FaUnderline,
  'Undo': FaUndo,
  'Undo Alt': FaUndoAlt,
  'Universal Access': FaUniversalAccess,
  'University': FaUniversity,
  'Unlink': FaUnlink,
  'Unlock': FaUnlock,
  'Unlock Alt': FaUnlockAlt,
  'Upload': FaUpload,
  'User': FaUser,
  'User Alt': FaUserAlt,
  'User Alt Slash': FaUserAltSlash,
  'User Astronaut': FaUserAstronaut,
  'User Check': FaUserCheck,
  'User Circle': FaUserCircle,
  'User Clock': FaUserClock,
  'User Cog': FaUserCog,
  'User Edit': FaUserEdit,
  'User Friends': FaUserFriends,
  'User Injured': FaUserInjured,
  'User Lock': FaUserLock,
  'User MD': FaUserMd,
  'User Minus': FaUserMinus,
  'User Ninja': FaUserNinja,
  'User Nurse': FaUserNurse,
  'User Plus': FaUserPlus,
  'User Secret': FaUserSecret,
  'User Shield': FaUserShield,
  'User Slash': FaUserSlash,
  'User Tag': FaUserTag,
  'User Tie': FaUserTie,
  'User Times': FaUserTimes,
  'Users': FaUsers,
  'Utensils': FaUtensils,
  'Utensil Spoon': FaUtensilSpoon,
  'Venus': FaVenus,
  'Venus Mars': FaVenusMars,
  'Vial': FaVial,
  'Vials': FaVials,
  'Video': FaVideo,
  'Video File': FaFileVideo,
  'Video Slash': FaVideoSlash,
  'Voicemail': FaVoicemail,
  'Volleyball Ball': FaVolleyballBall,
  'Volume Down': FaVolumeDown,
  'Volume Mute': FaVolumeMute,
  'Volume Off': FaVolumeOff,
  'Volume Up': FaVolumeUp,
  'Walking': FaWalking,
  'Wallet': FaWallet,
  'Warehouse': FaWarehouse,
  'Warning Circle': FaExclamationCircle,
  'Warning Triangle': FaExclamationTriangle,
  'Water': FaWater,
  'Weight': FaWeight,
  'Weight Hanging': FaWeightHanging,
  'Wheelchair': FaWheelchair,
  'WiFi': FaWifi,
  'Window': FaWindowMaximize,
  'Wine Bottle': FaWineBottle,
  'Wine Glass': FaWineGlass,
  'Wine Glass Alt': FaWineGlassAlt,
  'Won Sign': FaWonSign,
  'Wrench': FaWrench,
  'X-Ray': FaXRay,
  'Yen Sign': FaYenSign,
  'Yin Yang': FaYinYang
};

// Map icon names to colors - now using secondary color theme
// Note: These colors will be overridden by the secondary theme color in most cases
export const iconColorMap = Object.keys(iconComponentMap).reduce((acc, iconName) => {
  acc[iconName] = '#7e22ce';
  return acc;
}, {});

// List of all available icons for the selector (automatically sorted alphabetically)
export const availableIcons = Object.keys(iconComponentMap).map(name => ({
  name,
  component: iconComponentMap[name],
  color: iconColorMap[name]
}));

// Get icon component and color by name
export const getIconByName = (iconName) => {
  const IconComponent = iconComponentMap[iconName] || FaBook;
  const iconColor = iconColorMap[iconName] || '#7e22ce'; // Default to secondary color

  return {
    component: IconComponent,
    color: iconColor
  };
};
