import {
  // Actions
  FaSave,
  FaDownload,
  FaUpload,
  FaShare,
  FaExternalLinkAlt,
  FaStar,
  FaHeart,
  FaPrint,
  FaSearch as FaScan,
  FaSync,
  FaSyncAlt,
  FaCloudDownloadAlt as FaBackup,
  FaCloudUploadAlt as FaRestore,
  FaFileImport,
  FaFileExport,

  // Business & Finance
  FaDollarSign,
  FaEuroSign,
  FaYenSign,
  FaPoundSign,
  FaBitcoin,
  FaCreditCard,
  FaUniversity,
  FaReceipt,
  FaCalculator,
  FaChartLine as FaChartGrowth,
  FaBriefcase,
  FaFileInvoiceDollar,
  FaCoins,
  FaWallet,
  FaMoneyBillWave,
  FaMoneyCheckAlt,
  FaPiggyBank,
  FaHandHoldingUsd,
  FaBalanceScale,
  FaPercentage,

  // Communication
  FaPhone,
  FaPhoneAlt,
  FaMobileAlt,
  FaEnvelope,
  FaComment,
  FaComments,
  FaInbox,
  FaPaperPlane,
  FaFax,
  FaVoicemail,
  FaVideo as FaVideoCall,
  FaCommentDots as FaChat,
  FaUsers as FaForum,
  FaNewspaper,
  FaBullhorn as FaBroadcast,

  // Content Types
  FaFile,
  FaFileAlt,
  FaImage,
  FaVideo,
  FaLink,
  FaExpand,
  FaCompress,
  FaYoutube,
  FaFilePdf,
  FaFileWord,
  FaFileExcel,
  FaFilePowerpoint,
  FaFileAudio,
  FaPodcast as FaPodcastContent,
  FaEdit as FaBlog,

  // Education & Academic
  FaChalkboardTeacher,
  FaBookOpen,
  FaStickyNote,
  FaPencilAlt,
  FaPen,
  FaRuler,
  FaCalculator as FaCalculatorEducation,
  FaMicroscope,
  FaGlobeAmericas as FaGlobeEducation,
  FaBook as FaLibrary,
  FaAward as FaCertificateAlt,
  FaClipboardCheck,
  FaUserGraduate,

  // Entertainment & Media
  FaMusic,
  FaHeadphones as FaHeadphonesMedia,
  FaVolumeUp as FaSpeaker,
  FaMicrophone as FaMicrophoneMedia,
  FaCamera,
  FaVideo as FaVideoCamera,
  FaTv,
  FaBroadcastTower as FaRadio,
  FaTheaterMasks,
  FaFilm,
  FaGamepad,
  FaPlay,
  FaPodcast,
  FaGuitar,
  FaTicketAlt,

  // Food & Dining
  FaUtensils,
  FaCoffee,
  FaPizzaSlice,
  FaHamburger,
  FaAppleAlt,
  FaBreadSlice,
  FaWineGlass,
  FaBeer,
  FaConciergeBell,
  FaShoppingCart as FaGroceryCart,
  FaBlender,
  FaWeight,

  // Data & Charts
  FaList,
  FaTable,
  FaColumns,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaChartArea,
  FaDatabase,
  FaTachometerAlt,

  // Health & Medical
  FaHeartbeat,
  FaStethoscope,
  FaPills,
  FaSyringe,
  FaBandAid,
  FaHospital,
  FaAmbulance,
  FaFirstAid,
  FaThermometerHalf as FaMedicalThermometer,
  FaTint as FaBloodDrop,
  FaDna,
  FaVirus,
  FaMask,
  FaWheelchair,
  FaTooth,
  FaEye as FaMedicalEye,
  FaBrain as FaMedicalBrain,
  FaXRay,
  FaUserMd,
  FaPrescriptionBottle,

  // Home & Living
  FaHome,
  FaBuilding,
  FaBed,
  FaCouch,
  FaLightbulb as FaLamp,
  FaDoorOpen,
  FaKey as FaKeyHome,
  FaSeedling,
  FaWarehouse,
  FaBath,

  // Shopping & E-commerce
  FaShoppingCart as FaShoppingCartEcommerce,
  FaShoppingBag,
  FaCreditCard as FaCreditCardShopping,
  FaTag,
  FaBarcode,
  FaQrcode,
  FaStore,
  FaCashRegister,
  FaReceipt as FaReceiptShopping,
  FaPercentage as FaDiscount,
  FaFire as FaSale,
  FaGift,
  FaBox,
  FaTruck as FaDelivery,
  FaUndoAlt as FaReturns,

  // Sports & Recreation
  FaFootballBall,
  FaBasketballBall,
  FaFutbol,
  FaTableTennis,
  FaGolfBall,
  FaBaseballBall,
  FaSwimmer,
  FaGamepad as FaGameController,
  FaChess,
  FaBowlingBall,

  // Interface
  FaBars,
  FaSquare,
  FaCheck,
  FaTimes,
  FaCog,
  FaTrash,
  FaEdit,
  FaLayerGroup,
  FaFont,
  FaPlus,
  FaMinus,
  FaEye,
  FaEyeSlash,
  FaUndo,
  FaRedo,
  FaSearch,
  FaCopy,
  FaPaste,
  FaFilter,
  FaSort,
  FaTh as FaGridView,
  FaList as FaListView,
  FaIdCard as FaCardView,
  FaColumns as FaSidebar,
  FaWindowMaximize as FaModal,
  FaInfoCircle as FaTooltip,

  // Learning
  FaLightbulb,
  FaBook,
  FaQuestionCircle,
  FaGraduationCap,
  FaBrain,
  FaInfo,

  // Navigation
  FaArrowRight,
  FaArrowLeft,
  FaArrowUp,
  FaArrowDown,
  FaChevronRight,
  FaChevronLeft,
  FaChevronUp,
  FaChevronDown,
  FaArrowsAlt,
  FaArrowsAltH,

  // Notifications
  FaExclamationTriangle,
  FaExclamationCircle,
  FaInfoCircle,
  FaBell,
  FaBellSlash,
  FaTimesCircle,
  FaCheckCircle,

  // Security
  FaShieldAlt,
  FaKey,
  FaFingerprint,
  FaUserLock,
  FaUserShield,
  FaIdBadge,
  FaLock,
  FaUnlock,

  // Senses & Perception
  FaMicrophone,
  FaVolumeUp,
  FaHeadphones,
  FaGlasses,
  FaHandPaper,
  FaCommentDots,
  FaHandHoldingHeart,
  FaHandshake,

  // Social Media & Brands
  FaFacebook,
  FaTwitter,
  FaInstagram,
  FaLinkedin,
  FaYoutube as FaYoutubeBrand,
  FaTiktok,
  FaWhatsapp,
  FaTelegram,
  FaDiscord,
  FaSlack,
  FaGithub,
  FaGoogle,
  FaApple,
  FaMicrosoft,
  FaAmazon,

  // Time
  FaHourglassHalf,
  FaClock,
  FaStopwatch,
  FaHistory,
  FaCalendarAlt,
  FaCalendarCheck,
  FaClock as FaTimer,
  FaBell as FaAlarm,
  FaCalendarAlt as FaSchedule,
  FaExclamationTriangle as FaDeadline,
  FaBars as FaTimeline,
  FaClock as FaDuration,

  // Weather & Nature
  FaBolt,
  FaTint,
  FaCloud,
  FaThermometerHalf,
  FaSun,
  FaSnowflake,
  FaWind,
  FaCloudShowersHeavy as FaStorm,
  FaCloud as FaRainbow,
  FaTree,
  FaLeaf,
  FaSeedling as FaFlower,
  FaMountain,
  FaTint as FaOcean,
  FaFire,

  // Tools
  FaWrench,
  FaTools,
  FaToolbox,
  FaHammer,
  FaScrewdriver,
  FaCogs,
  FaSlidersH,
  FaMagic,

  // Transportation & Travel
  FaCar,
  FaBus,
  FaTrain,
  FaPlane,
  FaShip,
  FaBicycle,
  FaMotorcycle,
  FaTruck,
  FaTaxi,
  FaSubway,
  FaMapMarkedAlt,
  FaCompass,
  FaSuitcase,
  FaPassport,
  FaBed as FaHotel,
  FaGasPump,
  FaParking,
  FaTrafficLight,
  FaRoad,
  FaMapSigns,

  // Internet & Network
  FaWifi,
  FaGlobe,
  FaGlobeAmericas,
  FaServer,
  FaNetworkWired,
  FaEthernet,
  FaRss,
  FaCloud as FaCloudNetwork,
  FaDesktop,
  FaLaptop,
  FaMobile,
  FaTabletAlt,
  FaPlug,
  FaBroadcastTower
} from 'react-icons/fa';

// Material Design Icons for specific icons not available in FontAwesome
import {
  MdHearing,
  MdSchool,
  MdKitchen,
  MdStairs,
  MdMailOutline,
  MdDirectionsRun,
  MdDirectionsBike,
  MdFitnessCenter,
  MdEmojiEvents,
  MdMilitaryTech,
  MdGpsFixed,
  MdCasino,
  MdDownhillSkiing,
  MdWaves
} from 'react-icons/md';

// Map of icon names to display names (for UI), organized by category
export const ICON_CATEGORIES = {
  'Actions': {
    'save': 'Save',
    'download': 'Download',
    'upload': 'Upload',
    'share': 'Share',
    'external-link': 'External Link',
    'star': 'Star',
    'heart': 'Heart',
    'print': 'Print',
    'scan': 'Scan',
    'refresh': 'Refresh',
    'sync': 'Sync',
    'backup': 'Backup',
    'restore': 'Restore',
    'import': 'Import',
    'export': 'Export'
  },
  'Business & Finance': {
    'dollar-sign': 'Dollar',
    'euro-sign': 'Euro',
    'yen-sign': 'Yen',
    'pound-sign': 'Pound',
    'bitcoin': 'Bitcoin',
    'credit-card': 'Credit Card',
    'bank': 'Bank',
    'receipt': 'Receipt',
    'calculator': 'Calculator',
    'chart-growth': 'Growth Chart',
    'briefcase': 'Briefcase',
    'invoice': 'Invoice',
    'coins': 'Coins',
    'wallet': 'Wallet',
    'money-bill': 'Money Bill',
    'money-check': 'Check',
    'piggy-bank': 'Savings',
    'hand-money': 'Payment',
    'balance-scale': 'Balance',
    'percentage': 'Percentage'
  },
  'Communication': {
    'comment': 'Message',
    'comments': 'Comments',
    'envelope': 'Email',
    'fax': 'Fax',
    'inbox': 'Inbox',
    'mobile': 'Mobile',
    'paper-plane': 'Send',
    'phone': 'Phone',
    'phone-alt': 'Phone (Alt)',
    'voicemail': 'Voicemail',
    'video-call': 'Video Call',
    'chat': 'Chat',
    'forum': 'Forum',
    'newsletter': 'Newsletter',
    'broadcast': 'Broadcast'
  },
  'Content': {
    'file': 'File',
    'file-alt': 'Document',
    'image': 'Image',
    'video': 'Video',
    'link': 'Link',
    'expand': 'Expand',
    'compress': 'Compress',
    'youtube': 'YouTube',
    'pdf': 'PDF',
    'word': 'Word',
    'excel': 'Excel',
    'powerpoint': 'PowerPoint',
    'audio': 'Audio',
    'podcast-content': 'Podcast',
    'blog': 'Blog'
  },
  'Data & Charts': {
    'list': 'List',
    'table': 'Table',
    'columns': 'Columns',
    'chart-bar': 'Bar Chart',
    'chart-line': 'Line Chart',
    'chart-pie': 'Pie Chart',
    'chart-area': 'Area Chart',
    'database': 'Database',
    'dashboard': 'Dashboard',
  },
  'Education & Academic': {
    'school': 'School',
    'university': 'University',
    'classroom': 'Classroom',
    'book-open': 'Book',
    'notebook': 'Notebook',
    'pencil': 'Pencil',
    'pen': 'Pen',
    'ruler': 'Ruler',
    'calculator-education': 'Calculator',
    'microscope': 'Microscope',
    'globe-education': 'Globe',
    'library': 'Library',
    'certificate': 'Certificate',
    'test': 'Test',
    'graduate': 'Graduate'
  },
  'Entertainment & Media': {
    'music': 'Music',
    'headphones-media': 'Headphones',
    'speaker': 'Speaker',
    'microphone-media': 'Microphone',
    'camera': 'Camera',
    'video-camera': 'Video Camera',
    'tv': 'TV',
    'radio': 'Radio',
    'theater': 'Theater',
    'film': 'Film',
    'gaming': 'Gaming',
    'play': 'Play',
    'podcast': 'Podcast',
    'guitar': 'Guitar',
    'ticket': 'Ticket'
  },
  'Food & Dining': {
    'utensils': 'Utensils',
    'coffee': 'Coffee',
    'pizza': 'Pizza',
    'hamburger': 'Hamburger',
    'apple': 'Apple',
    'bread': 'Bread',
    'wine': 'Wine',
    'beer': 'Beer',
    'restaurant': 'Restaurant',
    'grocery-cart': 'Grocery Cart',
    'blender': 'Blender',
    'scale': 'Scale'
  },
  'Health & Medical': {
    'heartbeat': 'Heartbeat',
    'stethoscope': 'Stethoscope',
    'pills': 'Pills',
    'syringe': 'Syringe',
    'bandage': 'Bandage',
    'hospital': 'Hospital',
    'ambulance': 'Ambulance',
    'first-aid': 'First Aid',
    'medical-thermometer': 'Thermometer',
    'blood-drop': 'Blood Drop',
    'dna': 'DNA',
    'virus': 'Virus',
    'mask': 'Mask',
    'wheelchair': 'Wheelchair',
    'tooth': 'Tooth',
    'medical-eye': 'Eye Exam',
    'medical-brain': 'Brain Scan',
    'x-ray': 'X-Ray',
    'doctor': 'Doctor',
    'prescription': 'Prescription'
  },
  'Home & Living': {
    'home': 'Home',
    'apartment': 'Apartment',
    'bed': 'Bed',
    'sofa': 'Sofa',
    'lamp': 'Lamp',
    'door': 'Door',
    'key-home': 'Key',
    'garden': 'Garden',
    'garage': 'Garage',
    'bathroom': 'Bathroom',
    'kitchen': 'Kitchen',
    'living-room': 'Living Room',
    'bedroom': 'Bedroom',
    'stairs': 'Stairs',
    'roof': 'Roof',
    'fence': 'Fence',
    'mailbox': 'Mailbox'
  },
  'Interface': {
    'menu': 'Menu',
    'square': 'Square',
    'check': 'Check',
    'close': 'Close',
    'settings': 'Settings',
    'delete': 'Delete',
    'edit': 'Edit',
    'layers': 'Layers',
    'type': 'Type',
    'add': 'Add',
    'remove': 'Remove',
    'show': 'Show',
    'hide': 'Hide',
    'undo': 'Undo',
    'redo': 'Redo',
    'search': 'Search',
    'copy': 'Copy',
    'paste': 'Paste',
    'filter': 'Filter',
    'sort': 'Sort',
    'grid-view': 'Grid View',
    'list-view': 'List View',
    'card-view': 'Card View',
    'sidebar': 'Sidebar',
    'modal': 'Modal',
    'tooltip': 'Tooltip'
  },
  'Internet & Network': {
    'wifi': 'WiFi',
    'globe': 'Globe',
    'globe-americas': 'Globe Americas',
    'server': 'Server',
    'network-wired': 'Network Wired',
    'ethernet': 'Ethernet',
    'rss': 'RSS Feed',
    'cloud-network': 'Cloud Network',
    'desktop': 'Desktop Computer',
    'laptop': 'Laptop',
    'mobile-device': 'Mobile Device',
    'tablet': 'Tablet',
    'plug': 'Power Plug',
    'broadcast-tower': 'Broadcast Tower'
  },
  'Learning': {
    'lightbulb': 'Idea',
    'book': 'Book',
    'question': 'Question',
    'graduation-cap': 'Education',
    'brain': 'Knowledge',
    'info': 'Info',
  },
  'Navigation': {
    'double-arrow': 'Double Sided Arrow',
    'arrow-right': 'Arrow Right',
    'arrow-left': 'Arrow Left',
    'arrow-up': 'Arrow Up',
    'arrow-down': 'Arrow Down',
    'chevron-right': 'Chevron Right',
    'chevron-left': 'Chevron Left',
    'chevron-up': 'Chevron Up',
    'chevron-down': 'Chevron Down',
    'move': 'Move',
  },
  'Notifications': {
    'warning': 'Warning',
    'exclamation': 'Exclamation',
    'info-circle': 'Info Circle',
    'bell': 'Notification',
    'bell-off': 'Notification Off',
    'error': 'Error',
    'success': 'Success',
  },
  'Security': {
    'shield': 'Shield',
    'key': 'Key',
    'fingerprint': 'Fingerprint',
    'user-lock': 'User Lock',
    'user-shield': 'User Shield',
    'id-badge': 'ID Badge',
    'lock': 'Lock',
    'unlock': 'Unlock'
  },
  'Shopping & E-commerce': {
    'shopping-cart-ecommerce': 'Shopping Cart',
    'shopping-bag': 'Shopping Bag',
    'credit-card-shopping': 'Credit Card',
    'price-tag': 'Price Tag',
    'barcode': 'Barcode',
    'qr-code': 'QR Code',
    'store': 'Store',
    'cashier': 'Cashier',
    'receipt-shopping': 'Receipt',
    'discount': 'Discount',
    'sale': 'Sale',
    'gift': 'Gift',
    'package': 'Package',
    'delivery': 'Delivery',
    'returns': 'Returns'
  },
  'Social Media & Brands': {
    'facebook': 'Facebook',
    'twitter': 'Twitter',
    'instagram': 'Instagram',
    'linkedin': 'LinkedIn',
    'youtube-brand': 'YouTube',
    'tiktok': 'TikTok',
    'whatsapp': 'WhatsApp',
    'telegram': 'Telegram',
    'discord': 'Discord',
    'slack': 'Slack',
    'github': 'GitHub',
    'google': 'Google',
    'apple': 'Apple',
    'microsoft': 'Microsoft',
    'amazon': 'Amazon'
  },
  'Sports & Recreation': {
    'football': 'Football',
    'basketball': 'Basketball',
    'soccer': 'Soccer',
    'tennis': 'Tennis',
    'golf': 'Golf',
    'baseball': 'Baseball',
    'swimming': 'Swimming',
    'running': 'Running',
    'cycling': 'Cycling',
    'gym': 'Gym',
    'trophy': 'Trophy',
    'medal': 'Medal',
    'target': 'Target',
    'dice': 'Dice',
    'game-controller': 'Game Controller',
    'chess': 'Chess',
    'bowling': 'Bowling',
    'skiing': 'Skiing',
    'surfing': 'Surfing'
  },
  'Senses & Perception': {
    'ear': 'Ear',
    'eye': 'Eye',
    'microphone': 'Microphone',
    'volume-up': 'Volume',
    'headphones': 'Headphones',
    'glasses': 'Glasses',
    'hand': 'Hand',
    'comment-dots': 'Speaking',
    'comments': 'Conversation',
    'hand-holding-heart': 'Take Responsibility',
    'handshake': 'Agreement'
  },
  'Time': {
    'hourglass': 'Hourglass',
    'clock': 'Clock',
    'stopwatch': 'Stopwatch',
    'history': 'History',
    'calendar': 'Calendar',
    'calendar-check': 'Calendar Check',
    'timer': 'Timer',
    'alarm': 'Alarm',
    'schedule': 'Schedule',
    'deadline': 'Deadline',
    'timeline': 'Timeline',
    'duration': 'Duration'
  },
  'Transportation & Travel': {
    'car': 'Car',
    'bus': 'Bus',
    'train': 'Train',
    'plane': 'Plane',
    'ship': 'Ship',
    'bicycle': 'Bicycle',
    'motorcycle': 'Motorcycle',
    'truck': 'Truck',
    'taxi': 'Taxi',
    'subway': 'Subway',
    'map': 'Map',
    'compass': 'Compass',
    'luggage': 'Luggage',
    'passport': 'Passport',
    'hotel': 'Hotel',
    'gas-pump': 'Gas Station',
    'parking': 'Parking',
    'traffic-light': 'Traffic Light',
    'road': 'Road',
    'map-signs': 'Directions'
  },
  'Tools': {
    'wrench': 'Wrench',
    'toolset': 'Tools Set',
    'toolbox': 'Toolbox',
    'hammer': 'Hammer',
    'screwdriver': 'Screwdriver',
    'gears': 'Gears',
    'sliders': 'Sliders',
    'magic-wand': 'Magic Wand'
  },
  'Weather & Nature': {
    'lightning': 'Lightning Bolt',
    'water-drop': 'Water Drop',
    'rain-cloud': 'Rain Cloud',
    'thermometer': 'Thermometer',
    'sun': 'Sun',
    'snow': 'Snow',
    'wind': 'Wind',
    'storm': 'Storm',
    'rainbow': 'Rainbow',
    'tree': 'Tree',
    'leaf': 'Leaf',
    'flower': 'Flower',
    'mountain': 'Mountain',
    'ocean': 'Ocean',
    'fire': 'Fire'
  }
};

// Flatten categories into a single map for backward compatibility
export const ICON_NAME_MAP = Object.entries(ICON_CATEGORIES).reduce((acc, [, icons]) => {
  return { ...acc, ...icons };
}, {});

// Map icon keys to their components
export const ICONS = {
  // Actions
  'save': FaSave,
  'download': FaDownload,
  'upload': FaUpload,
  'share': FaShare,
  'external-link': FaExternalLinkAlt,
  'star': FaStar,
  'heart': FaHeart,
  'print': FaPrint,
  'scan': FaScan,
  'refresh': FaSyncAlt,
  'sync': FaSync,
  'backup': FaBackup,
  'restore': FaRestore,
  'import': FaFileImport,
  'export': FaFileExport,

  // Business & Finance
  'dollar-sign': FaDollarSign,
  'euro-sign': FaEuroSign,
  'yen-sign': FaYenSign,
  'pound-sign': FaPoundSign,
  'bitcoin': FaBitcoin,
  'credit-card': FaCreditCard,
  'bank': FaUniversity,
  'receipt': FaReceipt,
  'calculator': FaCalculator,
  'chart-growth': FaChartGrowth,
  'briefcase': FaBriefcase,
  'invoice': FaFileInvoiceDollar,
  'coins': FaCoins,
  'wallet': FaWallet,
  'money-bill': FaMoneyBillWave,
  'money-check': FaMoneyCheckAlt,
  'piggy-bank': FaPiggyBank,
  'hand-money': FaHandHoldingUsd,
  'balance-scale': FaBalanceScale,
  'percentage': FaPercentage,

  // Communication
  'comment': FaComment,
  'comments': FaComments,
  'envelope': FaEnvelope,
  'fax': FaFax,
  'inbox': FaInbox,
  'mobile': FaMobileAlt,
  'paper-plane': FaPaperPlane,
  'phone': FaPhone,
  'phone-alt': FaPhoneAlt,
  'voicemail': FaVoicemail,
  'video-call': FaVideoCall,
  'chat': FaChat,
  'forum': FaForum,
  'newsletter': FaNewspaper,
  'broadcast': FaBroadcast,

  // Content Types
  'file': FaFile,
  'file-alt': FaFileAlt,
  'image': FaImage,
  'video': FaVideo,
  'link': FaLink,
  'expand': FaExpand,
  'compress': FaCompress,
  'youtube': FaYoutube,
  'pdf': FaFilePdf,
  'word': FaFileWord,
  'excel': FaFileExcel,
  'powerpoint': FaFilePowerpoint,
  'audio': FaFileAudio,
  'podcast-content': FaPodcastContent,
  'blog': FaBlog,

  // Data & Charts
  'list': FaList,
  'table': FaTable,
  'columns': FaColumns,
  'chart-bar': FaChartBar,
  'chart-line': FaChartLine,
  'chart-pie': FaChartPie,
  'chart-area': FaChartArea,
  'database': FaDatabase,
  'dashboard': FaTachometerAlt,

  // Education & Academic
  'school': MdSchool,
  'university': FaUniversity,
  'classroom': FaChalkboardTeacher,
  'book-open': FaBookOpen,
  'notebook': FaStickyNote,
  'pencil': FaPencilAlt,
  'pen': FaPen,
  'ruler': FaRuler,
  'calculator-education': FaCalculatorEducation,
  'microscope': FaMicroscope,
  'globe-education': FaGlobeEducation,
  'library': FaLibrary,
  'certificate': FaCertificateAlt,
  'test': FaClipboardCheck,
  'graduate': FaUserGraduate,

  // Entertainment & Media
  'music': FaMusic,
  'headphones-media': FaHeadphonesMedia,
  'speaker': FaSpeaker,
  'microphone-media': FaMicrophoneMedia,
  'camera': FaCamera,
  'video-camera': FaVideoCamera,
  'tv': FaTv,
  'radio': FaRadio,
  'theater': FaTheaterMasks,
  'film': FaFilm,
  'gaming': FaGamepad,
  'play': FaPlay,
  'podcast': FaPodcast,
  'guitar': FaGuitar,
  'ticket': FaTicketAlt,

  // Food & Dining
  'utensils': FaUtensils,
  'coffee': FaCoffee,
  'pizza': FaPizzaSlice,
  'hamburger': FaHamburger,
  'apple': FaAppleAlt,
  'bread': FaBreadSlice,
  'wine': FaWineGlass,
  'beer': FaBeer,
  'restaurant': FaConciergeBell,
  'grocery-cart': FaGroceryCart,
  'blender': FaBlender,
  'scale': FaWeight,

  // Health & Medical
  'heartbeat': FaHeartbeat,
  'stethoscope': FaStethoscope,
  'pills': FaPills,
  'syringe': FaSyringe,
  'bandage': FaBandAid,
  'hospital': FaHospital,
  'ambulance': FaAmbulance,
  'first-aid': FaFirstAid,
  'medical-thermometer': FaMedicalThermometer,
  'blood-drop': FaBloodDrop,
  'dna': FaDna,
  'virus': FaVirus,
  'mask': FaMask,
  'wheelchair': FaWheelchair,
  'tooth': FaTooth,
  'medical-eye': FaMedicalEye,
  'medical-brain': FaMedicalBrain,
  'x-ray': FaXRay,
  'doctor': FaUserMd,
  'prescription': FaPrescriptionBottle,

  // Home & Living
  'home': FaHome,
  'apartment': FaBuilding,
  'bed': FaBed,
  'sofa': FaCouch,
  'lamp': FaLamp,
  'door': FaDoorOpen,
  'key-home': FaKeyHome,
  'garden': FaSeedling,
  'garage': FaWarehouse,
  'bathroom': FaBath,
  'kitchen': MdKitchen,
  'living-room': FaCouch,
  'bedroom': FaBed,
  'stairs': MdStairs,
  'roof': FaHome,
  'fence': FaSeedling,
  'mailbox': MdMailOutline,

  // Interface
  'menu': FaBars,
  'square': FaSquare,
  'check': FaCheck,
  'close': FaTimes,
  'settings': FaCog,
  'delete': FaTrash,
  'edit': FaEdit,
  'layers': FaLayerGroup,
  'type': FaFont,
  'add': FaPlus,
  'remove': FaMinus,
  'show': FaEye,
  'hide': FaEyeSlash,
  'undo': FaUndo,
  'redo': FaRedo,
  'search': FaSearch,
  'copy': FaCopy,
  'paste': FaPaste,
  'filter': FaFilter,
  'sort': FaSort,
  'grid-view': FaGridView,
  'list-view': FaListView,
  'card-view': FaCardView,
  'sidebar': FaSidebar,
  'modal': FaModal,
  'tooltip': FaTooltip,

  // Learning
  'lightbulb': FaLightbulb,
  'book': FaBook,
  'question': FaQuestionCircle,
  'graduation-cap': FaGraduationCap,
  'brain': FaBrain,
  'info': FaInfo,

  // Navigation
  'double-arrow': FaArrowsAltH,
  'arrow-right': FaArrowRight,
  'arrow-left': FaArrowLeft,
  'arrow-up': FaArrowUp,
  'arrow-down': FaArrowDown,
  'chevron-right': FaChevronRight,
  'chevron-left': FaChevronLeft,
  'chevron-up': FaChevronUp,
  'chevron-down': FaChevronDown,
  'move': FaArrowsAlt,

  // Notifications
  'warning': FaExclamationTriangle,
  'exclamation': FaExclamationCircle,
  'info-circle': FaInfoCircle,
  'bell': FaBell,
  'bell-off': FaBellSlash,
  'error': FaTimesCircle,
  'success': FaCheckCircle,

  // Security
  'shield': FaShieldAlt,
  'key': FaKey,
  'fingerprint': FaFingerprint,
  'user-lock': FaUserLock,
  'user-shield': FaUserShield,
  'id-badge': FaIdBadge,
  'lock': FaLock,
  'unlock': FaUnlock,

  // Shopping & E-commerce
  'shopping-cart-ecommerce': FaShoppingCartEcommerce,
  'shopping-bag': FaShoppingBag,
  'credit-card-shopping': FaCreditCardShopping,
  'price-tag': FaTag,
  'barcode': FaBarcode,
  'qr-code': FaQrcode,
  'store': FaStore,
  'cashier': FaCashRegister,
  'receipt-shopping': FaReceiptShopping,
  'discount': FaDiscount,
  'sale': FaSale,
  'gift': FaGift,
  'package': FaBox,
  'delivery': FaDelivery,
  'returns': FaReturns,

  // Social Media & Brands
  'facebook': FaFacebook,
  'twitter': FaTwitter,
  'instagram': FaInstagram,
  'linkedin': FaLinkedin,
  'youtube-brand': FaYoutubeBrand,
  'tiktok': FaTiktok,
  'whatsapp': FaWhatsapp,
  'telegram': FaTelegram,
  'discord': FaDiscord,
  'slack': FaSlack,
  'github': FaGithub,
  'google': FaGoogle,
  'apple': FaApple,
  'microsoft': FaMicrosoft,
  'amazon': FaAmazon,

  // Sports & Recreation
  'football': FaFootballBall,
  'basketball': FaBasketballBall,
  'soccer': FaFutbol,
  'tennis': FaTableTennis,
  'golf': FaGolfBall,
  'baseball': FaBaseballBall,
  'swimming': FaSwimmer,
  'running': MdDirectionsRun,
  'cycling': MdDirectionsBike,
  'gym': MdFitnessCenter,
  'trophy': MdEmojiEvents,
  'medal': MdMilitaryTech,
  'target': MdGpsFixed,
  'dice': MdCasino,
  'game-controller': FaGameController,
  'chess': FaChess,
  'bowling': FaBowlingBall,
  'skiing': MdDownhillSkiing,
  'surfing': MdWaves,

  // Senses & Perception
  'ear': MdHearing,
  'eye': FaEye,
  'microphone': FaMicrophone,
  'volume-up': FaVolumeUp,
  'headphones': FaHeadphones,
  'glasses': FaGlasses,
  'hand': FaHandPaper,
  'comment-dots': FaCommentDots,
  'comments': FaComments,
  'hand-holding-heart': FaHandHoldingHeart,
  'handshake': FaHandshake,

  // Time
  'hourglass': FaHourglassHalf,
  'clock': FaClock,
  'stopwatch': FaStopwatch,
  'history': FaHistory,
  'calendar': FaCalendarAlt,
  'calendar-check': FaCalendarCheck,
  'timer': FaTimer,
  'alarm': FaAlarm,
  'schedule': FaSchedule,
  'deadline': FaDeadline,
  'timeline': FaTimeline,
  'duration': FaDuration,

  // Transportation & Travel
  'car': FaCar,
  'bus': FaBus,
  'train': FaTrain,
  'plane': FaPlane,
  'ship': FaShip,
  'bicycle': FaBicycle,
  'motorcycle': FaMotorcycle,
  'truck': FaTruck,
  'taxi': FaTaxi,
  'subway': FaSubway,
  'map': FaMapMarkedAlt,
  'compass': FaCompass,
  'luggage': FaSuitcase,
  'passport': FaPassport,
  'hotel': FaHotel,
  'gas-pump': FaGasPump,
  'parking': FaParking,
  'traffic-light': FaTrafficLight,
  'road': FaRoad,
  'map-signs': FaMapSigns,

  // Tools
  'wrench': FaWrench,
  'toolset': FaTools,
  'toolbox': FaToolbox,
  'hammer': FaHammer,
  'screwdriver': FaScrewdriver,
  'gears': FaCogs,
  'sliders': FaSlidersH,
  'magic-wand': FaMagic,

  // Weather & Nature
  'lightning': FaBolt,
  'water-drop': FaTint,
  'rain-cloud': FaCloud,
  'thermometer': FaThermometerHalf,
  'sun': FaSun,
  'snow': FaSnowflake,
  'wind': FaWind,
  'storm': FaStorm,
  'rainbow': FaRainbow,
  'tree': FaTree,
  'leaf': FaLeaf,
  'flower': FaFlower,
  'mountain': FaMountain,
  'ocean': FaOcean,
  'fire': FaFire,

  // Internet & Network
  'wifi': FaWifi,
  'globe': FaGlobe,
  'globe-americas': FaGlobeAmericas,
  'server': FaServer,
  'network-wired': FaNetworkWired,
  'ethernet': FaEthernet,
  'rss': FaRss,
  'cloud-network': FaCloudNetwork,
  'desktop': FaDesktop,
  'laptop': FaLaptop,
  'mobile-device': FaMobile,
  'tablet': FaTabletAlt,
  'plug': FaPlug,
  'broadcast-tower': FaBroadcastTower
};
